version: "3.8"

services:
    nginx:
        image: nginx:1.10.3
        network_mode: host
        restart: "always"
        ports:
            - "80:80"
        volumes:
            - "./Nginx/marketplace.dev.template:/etc/nginx/conf.d/marketplace.dev.template"
            - "marketplace_storage:/var/www/html"
        environment:
            - NGNIX_HOST=${serverName}
        command: /bin/bash -c "cat /etc/nginx/conf.d/marketplace.dev.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
volumes:
  marketplace_storage:
