version: "3.8"

services:
  db_marketplace:
    image: postgres:11.4
    network_mode: host
    volumes:
      - marketplace_db:/var/lib/postgresql/data
      - database_run:/var/run/postgresql
      - ./db_backups:/opt/db_backups
    environment:
      - "POSTGRES_USER:${postgresUser}"
      - "POSTGRES_PASSWORD:${postgresPassword}"
      - "POSTGRES_DB:${postgresDatabase}"
    ports:
      - "${postgresPort}:5432"
    restart: "always"
  marketplace:
    build: 
      context: ./marketplace
      args:
        - railsEnv
        - rackEnv
        - gitUrl
        - hostAppDir
    volumes:
        - database_run:/var/run/postgresql
        - marketplace_storage:/var/opt/marketplace
    environment:
      - "HOST_PRODUCTION=${serverName}"
      - "SMTP_DOMAIN=${smtpDomain}"
      - "SENDGRID_PASSWORD=${sendGridPassword}"
      - "POSTGRES_DATABASE=${postgresDatabase}"
      - "POSTGRES_USERNAME=${postgresUser}"
      - "POSTGRES_PASSWORD=${postgresPassword}"
    network_mode: host
    depends_on:
      - db_marketplace
    restart: "always"
volumes:
  marketplace_db:
  marketplace_storage:
  database_run:
  certbot-etc:
  certbot-var:
